// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package search

type Cve struct {
	ID          *string `json:"Id"`
	Description *string `json:"Description"`
	Severity    *string `json:"Severity"`
}

type CVEResultForImage struct {
	Tag     *string `json:"tag"`
	CVEList []*Cve  `json:"CVEList"`
}

type ImgResultForCve struct {
	Name *string   `json:"name"`
	Tags []*string `json:"tags"`
}
